name: Build and test Python from Makefile

on:
  push:
    branches: 
      - main
  pull_request:
    branches: '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: pip install poetry
    - name: Build and run Python tests
      run: make py_tests
