name: C/C++ CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: make c_tests
