name: Deploy version to pypi
on:
  push:
    branches: 
      - master
      - streamline_process

jobs:
  publish:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Build package
        run: poetry build -f sdist
      - name: Test package
        run: poetry run pytest
      - name: publish to pypi
        run: poetry publish -r testpypi -u __token__ -p ${{ secrets.PYPI_TEST_TOKEN }}
