name: Deploy sdist to pypi
on:
  push:
    branches:
      - main

jobs:
  publish:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'nodeploy')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.7
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Build package
        run: poetry build -f sdist
      - name: Test package
        run: poetry run test
      - name: publish to pypi
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
