name: Check sdist builds and works
on: pull_request

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: make a clean sdist
        run: |
            rm -rf dist
            poetry build --format sdist
      - name: do a clean install
        run: |
            virtualenv venv
            venv/bin/pip install dist/exact_cover-*.tar.gz
            venv/bin/pip install pytest
            venv/bin/pip install hypothesis
            venv/bin/python -m pytest tests/test_exact_cover.py
