name: Check sdist builds and works (Windows)
on: pull_request

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
            pip install poetry==1.1.11
      - name: make a clean sdist
        run: |
            poetry -V
            poetry install
            poetry build --format sdist
      - name: do a clean install
        run: |
            virtualenv venv
            $filename = ls dist/ | Select-Object -ExpandProperty Name
            venv/scripts/pip install "dist/$filename"
            venv/scripts/pip install pytest
            venv/scripts/pip install hypothesis
            venv/scripts/python -m pytest tests/test_exact_cover.py
