name: Check sdist builds and works
on: pull_request

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: make a clean sdist
        run: |
            poetry build --format sdist
      - name: do a clean install
        run: |
            virtualenv venv
            venv/bin/pip install dist/exact_cover-*.tar.gz
            venv/bin/pip install pytest
            venv/bin/python -m pytest tests/test_exact_cover.py
