name: Python checks and tests

on:
  push:
    branches: 
      - master
  pull_request:
    branches: '**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install poetry
      run: pip install poetry
    - name: Install requirements
      run: poetry install
    - name: Lint with flake8
      run: poetry run flake8
