# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python build

on:
  push:
    branches: 
      - master
      - fix_build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r build_requirements.txt
    - name: Build wheel
      run: |
        cd exact_cover_np
        python setup.py bdist_wheel
    - name: Archive wheel
      uses: actions/upload-artifact@v2
      with:
        name: bdist_wheel
        path: exact_cover_np/dist/*.whl
