
name: Python build

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
    - name: Build wheel
      run: |
        poetry build
    - name: Archive wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: exact_cover*.whl
