# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    python-version: 3.7

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ python-version }}
    - name: Install package
      run: |
        cd exact_cover_np
        python setup.py bdist_wheel
    - name: Archive wheel
      uses: actions/upload-artifact@v2
      with:
        name: bdist_wheel
        path: exact_cover_np/dist/*.whl
