name: Python checks and tests

on:
  push:
    branches: 
      - master
  pull_request:
    branches: '**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.4
    - name: Lint with flake8
      run: |
        poetry run flake8
